version: '3'

services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_DB_NAME=${MONGODB_DB}
      - MONGO_DB_USERNAME=${MONGODB_USER}
      - MONGO_DB_PASSWORD=${MONGODB_PASS}
    networks:
      - reviews-network
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - reviews-network

  reviews-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_DB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/${MONGODB_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBITMQ_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - API_QUEUE=${API_QUEUE}
      - AMAZON_QUEUE=${AMAZON_QUEUE}
    networks:
      - reviews-network
    volumes:
      - type: volume
        source: api_logs
        target: /app/logs
  
  reviews-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - reviews-network

  reviews-scrapper:
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    environment:
      - MONGO_DB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/${MONGODB_DB}
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
      - DEBUG=true
      - HUB_MODE=true
      - PRODUCTS_TO_SEARCH=${PRODUCTS_TO_SEARCH}
      - REVIEWS_TO_READ=${REVIEWS_TO_READ}
      - API_QUEUE=${API_QUEUE}
      - AMAZON_QUEUE=${AMAZON_QUEUE}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - type: volume
        source: scrapper_logs
        target: /app/logs
    networks:
      - reviews-network

  selenium-hub:
    image: selenium/hub:latest
    ports: 
      - "7900:7900"
      - "4444:4444"
    networks:
      - reviews-network

  chrome-node:
    image: selenium/node-chrome:4.17.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - shm-size="2g"
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - VNC_NO_PASSWORD=1
    networks:
      - reviews-network
    depends_on:
      - selenium-hub
    deploy:
      mode: replicated
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: brian
        RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - reviews-network
      
networks:
  reviews-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: mongo_data
  MONGO_CONFIG:
    name: mongo_config
  scrapper_logs:
    name: reviews_scrapper_logs
  api_logs:
    name: reviews_api_logs  