version: '3'

services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DB_NAME=reviews
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - reviews-network
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - reviews-network

  reviews-api:
    image: reviews-api:latest
    ports:
      - "4000:4000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCRAPPER_URL=http://reviews-scrapper:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REVIEWS_BACKOFFICE_URL=http://reviews-front:3000
    networks:
      - reviews-network
  
  reviews-front:
    image: reviews-front:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://reviews-api:4000
      - NEXT_PUBLIC_SCRAPPER_URL=http://reviews-scrapper:8000
    networks:
      - reviews-network

  reviews-scrapper:
    image: reviews-scrapper:latest
    ports: 
      - "5000:8000"
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - REVIEWS_HUB_URL=http://reviews-api:4000
      - REVIEWS_BACKOFFICE_URL=http://reviews-front:3000
      - DEBUG=true
    networks:
      - reviews-network

  selenium-hub:
    image: selenium/hub:latest
    ports: 
      - "4442:4442"
      - "4444:4444"
    networks:
      - reviews-network

  chrome-node:
    image: selenium/node-chrome:4.0.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - shm-size="2g"
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - reviews-network
    depends_on:
      - selenium-hub


networks:
  reviews-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: mongo_data
  MONGO_CONFIG:
    name: mongo_config