version: '3'

services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DB_NAME=reviews
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - reviews-network
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - reviews-network

  selenium-hub:
    image: selenium/hub:latest
    ports: 
      - "7900:7900"
      - "4444:4444"
    networks:
      - reviews-network

  chrome-node:
    image: selenium/node-chrome:4.17.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - shm-size="2g"
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - VNC_NO_PASSWORD=1
    networks:
      - reviews-network
    depends_on:
      - selenium-hub
    deploy:
      mode: replicated
      replicas: 1
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: brian
        RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - reviews-network
      
networks:
  reviews-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: mongo_data
  MONGO_CONFIG:
    name: mongo_config
  scrapper_logs:
    name: reviews_scrapper_logs
  api_logs:
    name: reviews_api_logs  